# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import guide_pb2 as guide__pb2


class GuideStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNextStep = channel.unary_unary(
                '/Guide/GetNextStep',
                request_serializer=guide__pb2.CarState.SerializeToString,
                response_deserializer=guide__pb2.Step.FromString,
                )


class GuideServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetNextStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GuideServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNextStep': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextStep,
                    request_deserializer=guide__pb2.CarState.FromString,
                    response_serializer=guide__pb2.Step.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Guide', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Guide(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetNextStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Guide/GetNextStep',
            guide__pb2.CarState.SerializeToString,
            guide__pb2.Step.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
